version: '3.8'

services:
  quotation:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 8080
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - "8080:8080"